### ISSUE TITLE
To set up and run in colab

### ISSUE THREAD

**Issue by Hir98** [argmaxinc/whisperkittools#1]
How can we run this in colab ? I have clone this repo and try to run generate_model.py scripts but not able to generate model.

So can you please provide me steps to generate model in coreml?

**Comment by atiorh** [comment]
Hi @Hir98, the `whisperkit-generate-model` workflow (backed by `generate_model.py`) requires Apple Silicon so you won't be able to run on a Colab (linux) session.

If you have a Mac, you should be able to run it locally. Let me know if you hit any snags :)

**Comment by hiral-t** [comment]
@atiorh  Is it feasible to generate .mlmodel files in Google Colab using alternative methods? I currently have Linux installed and attempted to generate .mlmodel files using a specific repository. I'm wondering if it's possible to adapt and modify the code from this repository to run effectively in the Google Colab environment. Could you provide guidance on how to accomplish this?
