### ISSUE TITLE
TypeError: Cannot multiply sequence by non-int of type 'float' during model conversion

### ISSUE THREAD

**Issue by wwang108** [argmaxinc/whisperkittools#10]
I encountered a TypeError while attempting to convert a Hugging Face Whisper model to WhisperKit (Core ML) format using the whisperkit-generate-model command as described in the README. The error occurred in the self-attention mechanism of the audio encoder during unit testing.

Steps to Reproduce

Followed the instructions in the README to set up the environment and dependencies.

Ran the conversion command: whisperkit-generate-model --model-version <model-version> --output-dir <output-dir>

Encountered the error during the setUpClass of tests.test_audio_encoder.TestWhisperAudioEncoder.

Received a TypeError indicating an issue with multiplying a sequence by a non-integer float type. The full error message is as follows:

TypeError: can't multiply sequence by non-int of type 'float'

The error traceback points to the following lines:

File "/opt/anaconda3/envs/whisperkit/lib/python3.11/site-packages/argmaxtools/_sdpa.py", line 135, in sdpa
    mh_w = [_mh_w * self.qk_denom for _mh_w in mh_w]

**Comment by atiorh** [comment]
Thanks for the report! I just pushed a hot-fix to argmaxtools. Could you please do `pip install argmaxtools --upgrade` and try again?

**Comment by wwang108** [comment]
Thanks, Now it works!
