### ISSUE TITLE
Replace map with imap to get tqdm progress bar

### ISSUE THREAD

**Issue by wooster** [argmaxinc/whisperkittools#15]
When evaluating large datasets, it looks like you were trying to create a progress bar:

https://github.com/argmaxinc/whisperkittools/blob/33d167fbdbf00b5bf47a8748b7b368ed1ddd57f5/whisperkit/evaluate/evaluate.py#L56-L60

If you replace `map` with `imap` the progress bar will show up. Without it, at least on my config, it doesn't show up.

**Comment by atiorh** [comment]
Thanks for the find!
