### ISSUE TITLE
After selecting Chinese in Stream Transcribe, the results are not accurate.

### ISSUE THREAD

**Issue by YiLee01** [argmaxinc/whisperkittools#7]
Chinese has simplified Chinese and traditional Chinese. When choosing Chinese in Stream Transcribe, only traditional Chinese is output. Please support simplified Chinese. 🩷

**Comment by atiorh** [comment]
Thanks for the note! We do not yet train Whisper on new languages. We deploy Whisper models from Open AI. https://github.com/openai/whisper or Open AI forums might be a better place to raise this issue.

**Comment by takan1** [comment]
@atiorh so if the original models work in other languages on original whisper library, the same model with whisperkittools should work the same as well, correct?
