### ISSUE TITLE
How to do streaming with whisperkittools

### ISSUE THREAD

**Issue by takan1** [argmaxinc/whisperkittools#8]
Hi, I'd like to use whisperkittools in streaming format on my Mac. Is it possible?

**Comment by atiorh** [comment]
Hi! `whisperkittools` is not meant for direct inference consumption. It has an inference pipeline to run quality benchmarks based on the [WhisperKit-CLI](https://github.com/argmaxinc/WhisperKit?tab=readme-ov-file#swift-cli) but it is not wired for streaming.

**Comment by atiorh** [comment]
Please do `brew install whisperkit-cli` and use it with `--stream`
