### ISSUE TITLE
How it compare to whisper-streaming and whisperlive?

### ISSUE THREAD

**Issue by takan1** [argmaxinc/whisperkittools#9]
There are already multiple repos that aim streaming for whisper models like [whisper streaming](https://github.com/ufal/whisper_streaming) and [whisperlive](https://github.com/collabora/WhisperLive). What is the differentiator and how it compares wrt latency and quality of transcription?

**Comment by atiorh** [comment]
Hi! `whisper_streaming` has the same token confirmation logic as our Eager Mode. We cite them [here as prior work](https://x.com/argmaxinc/status/1774809790595932658).
